import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./parts/navbar";
import Footer from "./parts/footer";
import { AosInit } from "./components/aos";
import ReduxProvider from "./ReduxProvider";

export const metadata: Metadata = {
  title: "Mochichi shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa">
      <body>
        <ReduxProvider>
          <AosInit />
          <Navbar />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
